create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10, 2) not null default 0,
  image text,
  quantity integer not null default 0,
  status text not null default 'Active'
);

alter table public.products
  add column if not exists price numeric(10, 2) not null default 0,
  add column if not exists image text,
  add column if not exists quantity integer not null default 0,
  add column if not exists status text not null default 'Active';